### ISSUE TITLE
Meaninglessness of font with COLR+CBDT tables in Android 13+

### ISSUE THREAD

**Issue by VladWinner** [googlefonts/nanoemoji#437] opened 2022-10-02 13:10 UTC
Looks like `maximum_color` command just useless for Android 13 because this OS prioritizes the display of CBDT instead of COLR.

Android 13, COLR font (left) vs COLR+CBDT font (right):
![image](https://user-images.githubusercontent.com/13555921/193455623-54d63e77-cf9a-40b9-a363-d54225797f2b.png)

I used this command from README.md to ensure compatibility with previous Android versions which does not support COLR:
`maximum_color --bitmaps my_colr_font.ttf`

**Comment by anthrotype** [comment] 2022-10-03 11:49
Chrome has a similar issue that it prefers CBDT over COLR (as we mention in the nanoemoji's README): https://bugs.chromium.org/p/chromium/issues/detail?id=1315537

Not surpriosed that Android has the same problem, given it also relies on a similar font stack.

The root of the problem can be traced to the interaction Skia and Freetype, see https://bugs.chromium.org/p/skia/issues/detail?id=12945#c_ts1644833236 and https://gitlab.freedesktop.org/freetype/freetype/-/issues/1142

Maybe we should update the README accordingly until the issue is fixed upstream. /cc @rsheeter

**Comment by anthrotype** [comment] 2022-10-03 11:51
@VladWinner for now, there's nothing the font compiler can do to work around this, you'd need two distinct fonts, one with COLR and without CBDT, the other viceversa

**Comment by rsheeter** [comment] 2022-10-03 15:04
+1 to update readme, that's a bit of a nasty surprise.

**Comment by anthrotype** [comment] 2022-10-03 16:13
Updated README.md accordingly, PTAL https://github.com/googlefonts/nanoemoji/commit/cefcacd3d7dbe7e02d71ed433afd28cbd1708f50

**Comment by rsheeter** [comment] 2022-10-03 16:24
LGTM. I think that means there is nothing further to do to nanoemoji so closing. Please reopen if I'm mistaken.

**Closed by rsheeter** 2022-10-03 16:24 UTC
