### ISSUE TITLE
Svg font does not support gradientTransform in Safari

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#268] opened 2021-04-09 16:55 UTC
`nanoemoji --color_format=untouchedsvg`

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
  <defs>
    <linearGradient id="b" gradientUnits="userSpaceOnUse" x1="98.95" x2="123.82" y1="68.26" y2="93.14">
      <stop offset="0" stop-color="#2d50ff"/>
      <stop offset="1" stop-color="#61bef1"/>
    </linearGradient>
    <linearGradient id="e" gradientTransform="scale(-1 1)" gradientUnits="userSpaceOnUse" x1="-29.06" x2="-4.18" y1="68.26" y2="93.14">
      <stop offset="0" stop-color="#2d50ff"/>
      <stop offset="1" stop-color="#61bef1"/>
    </linearGradient>
  </defs>
  <path fill="url(#b)" d="M108.49,93.14 C104.25,88.9 97.25,70 99,68.26 S119.64,73.56 123.87,77.8 A10.84 10.84 0 1 1 108.54,93.14 Z"/>
  <path fill="url(#e)" d="M19.51,93.14 C23.75,88.9 30.75,70 29.05,68.26 S8.41,73.56 4.18,77.8 A10.84 10.84 0 0 0 19.51,93.14 Z"/>
</svg>
```

## Safari
![image](https://user-images.githubusercontent.com/2784308/114214859-73fcf080-9997-11eb-8b0a-157a6cd36ee9.png)

## Firefox
![image](https://user-images.githubusercontent.com/2784308/114216121-0fdb2c00-9999-11eb-90a4-405c66694bec.png)

## Adobe Photoshop

![image](https://user-images.githubusercontent.com/2784308/114214867-77907780-9997-11eb-9d84-702130236f9e.png)

**Comment by yisibl** [comment] 2021-04-12 16:16
Thanks @litherum for providing a solution in https://twitter.com/Litherum/status/1381638423237156868

**Comment by anthrotype** [comment] 2021-04-12 16:32
actually, it's more a workaround than a "solution".

From the Twitter conversation, as far as I understand, there's a problem in Safari's OT-SVG implementation whereby it assumes that a matrix is degenerate (i.e. can't be inverted) whenever the function [CGAffineTransformInvert](https://developer.apple.com/documentation/coregraphics/1455264-cgaffinetransforminvert?language=objc) returns the input parameter unchanged. But that's wrong, because there are valid matrices whose inverse is themeselves, e.g. the one in the example SVG ("scale(-1 1)").

@litherum suggests that we "tweak the values in the matrix so the matrix’s inverse doesn’t equal itself". Not exactly sure what that means.

Is the bug going to be fixed or is it already fixed in Safari? I could only test and reproduce this issue with Safari 14.0 (15610.1.28.1.9, 15610) on macOS Catalina 10.15.7. I haven't tried on later versions of OS/browser.

Maybe we could preempt such situation by checking if gradientTransform contain such special matrices whose inverse is equal to itself but whose determinant is non-zero (as such valid, non-degenerate matrices), and pre-apply them to the gradient geometry, thus removing the offending gradientTransform. This works only in so far as they keep the circles as circles (don't squash them to ellipses or lines), which it does in this flip case ("scale(-1, 1)") but I'm not sure if this holds true all the time.

**Comment by litherum** [comment] 2021-04-12 16:40
Just add 0.00001 to one of the matrix components. This will trick us into thinking the matrix is invertible.

**Closed** 2021-04-15 13:00 UTC
