### ISSUE TITLE
Explore what default clip box quantization should be

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#312] opened 2021-08-03 15:32 UTC
Making it >1 should increase box sharing at minimal cost

Edit: See #311for addition of clip boxes.

**Comment by rsheeter** [comment] 2021-08-05 20:56
Tested with noto-glyf_colr_1.toml from the color-fonts repo:

```
Quant     #Boxes
 1        1172
 8         930
16         709
```

**Comment by rsheeter** [comment] 2021-08-05 20:58
I might need to draw all the boxes to convince myself we *really* need 700+ boxes for Noto Emoji. It would be somewhat interesting to try giving a budget: you can have 16 boxes, seek to minimize wasted (excessively large) boxes.

**Comment by anthrotype** [comment] 2021-08-06 10:52
just to put things in perspective, if you compare [noto-glyf_colr_1.ttf](https://github.com/googlefonts/color-fonts/blob/main/fonts/noto-glyf_colr_1.ttf) as built on 17 May 2021 (without ClipList, but with non-empty base glyf glyphs containing the color glyph extents) with the new font built with the new ClipList (and empty base glyf glyphs, no quantization), you'll see that

1) the sum of glyf + htmx + loca table sizes went down from 4,169,969 bytes to 3,956,848, that is 213,121 bytes or more than -200KB of savings
2) the size of the compiled ClipList (all the ClipRecords + all the ClipBoxes) in the new font is merely 27,031 bytes or about 27KB, i.e. much less than the 200KB we saved earlier. You can measure like this:

```python
from fontTools.ttLib.tables.otBase import OTTableWriter
from fontTools.ttLib import TTFont

font = TTFont("../color-fonts/fonts/noto-glyf_colr_1.new.ttf")
writer = OTTableWriter(tableTag="COLR")
font["COLR"].table.ClipList.compile(writer, font)
clipData = writer.getAllData()
print(len(clipData))
````

It's true we are seeing an increase in the overall length of the COLR table _as a whole_ -- from 1,054,030 in the original font to 1,364,730 in the new one (+310,700 bytes), but I suspect the cause is not in the addition of a ClipList.

**Comment by rsheeter** [comment] 2021-08-06 17:55
I believe ClipList should be a filesize win (I suppose we could confirm by compiling with latest code and the old style of bbox restored), was just surprised at quite how many distinct boxes we're getting for emoji.

**Comment by anthrotype** [comment] 2021-08-09 13:44
> we could confirm by compiling with latest code and the old style of bbox restored

I did just that, ie. reverted the nanoemoji PR where we added support for ClipList and pinned fonttools and ufo2ft to the versions immediately preceding the ones where ClipList support was added, and it confirmed my calculations above.
The size of the COLR table without ClipList becomes 1,337,719 -- down **-27,011 bytes** from the 1,364,730 of the font that uses ClipList (my guess was off by only 20 bytes).

**Comment by anthrotype** [comment] 2021-08-09 13:53
As for the _total_ file size of the font built with ClipList-support reverted (but still using the new non-glyf, PaintTransform-based shape reuse), that's 5,437,576 bytes. Whereas the original font as checked in color-fonts repo was 5,281,264.
Therefore, when we _don't_ have ClipList the result is still +156,312 bytes bigger. The font with ClipList (and new PaintTransform-based reuse) was only around +95KB bigger than the baseline.
This confirm ClipList is still a win, and we should rather focus on #316

**Comment by rsheeter** [comment] 2021-08-09 18:09
> This confirm ClipList is still a win

Great, ty for checking. Nice when things work out as expected. IMO we should set a different default and call it a day for this issue?

**Comment by anthrotype** [comment] 2021-08-10 16:30
> a different default

Sure, which one though?

**Comment by rsheeter** [comment] 2021-08-10 16:53
Per f2f perhaps None default, which means 2% (rounded) of upem, user specifies value as they do today

**Closed** 2021-08-10 19:55 UTC
