### ISSUE TITLE
Maximizing color for FoldIt 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/nanoemoji#438] opened 2022-10-13 16:20 UTC
https://github.com/SophiaDesign/Foldit by @sophiadesign is a new variable color font that makes extensive use of color variations (amusingly in a way to create the illusion that as the weight (and natural width) changes, the gradients look like they don't change, which requires them TO change, ahaha) 

I heard today from @m4rc1e @vv-monsalve @RosaWagner that `maximum_color` doesn't work with it, and mentioned this to @rsheeter on chat and he thought this is feasible to address and I should file a bug to discuss and track resolution :)

**Comment by anthrotype** [comment] 2022-10-13 16:36
The "fix" would be to ignore `PaintVar*` tables and take the equivalent static paint tables, thus discarding all deltas and only encoding the default instance in the generated SVG table, because the latter does not support variations (and probably never will).

Closing as duplicate of https://github.com/googlefonts/nanoemoji/issues/426

**Closed by anthrotype** 2022-10-13 16:36 UTC
