### ISSUE TITLE
Support SBIX and CBDT/CBLC formats

### ISSUE THREAD

**Issue by yisibl** [googlefonts/nanoemoji#257] opened 2021-03-12 11:16 UTC

**Comment by rsheeter** [comment] 2021-03-18 17:20
+1, this is useful

**Comment by mavit** [comment] 2021-03-25 23:02
Duplicate of #88?

**Comment by rsheeter** [comment] 2022-01-16 20:27
> Duplicate of #88?

Yes indeed!

**Closed by rsheeter** 2022-01-16 20:27 UTC
